# Common usecase

FROM maven:3.9.5-eclipse-temurin-21-alpine AS build

# Set the working directory inside the container
WORKDIR /app

# Copy the project's pom.xml and initial source code to the container
COPY pom.xml .
COPY src ./src

# Run Maven package phase, which builds the application and dependencies
RUN mvn clean package

# main
FROM eclipse-temurin:21-jre-alpine as customjdk

RUN mkdir /app

COPY --from=build /app/target/*.jar /app/app.jar
WORKDIR /app

ENTRYPOINT [ "java","-jar", "/app/app.jar" ]